
name: RDP
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ngrok & RDP
        run: |
          curl -s https://raw.githubusercontent.com/CYB3RKING/RDP/main/setup.sh | bash
    